spring:
  cloud:
    azure:
      storage:
        account:
          name: devstoreaccount1
          key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
        queue:
          endpoint: http://127.0.0.1:10001/devstoreaccount1
          input:
            name: 'input-queue'
          output:
            name: 'output-queue'