spring:
  cloud:
    azure:
      storage:
        queue:
          endpoint: http://127.0.0.1:10001/devstoreaccount1
          input:
            name: 'input-queue'
          output:
            name: 'output-queue'