spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 80