name: AI sever CI/CD - Build and Deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: chat-ai-server-webapp

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: 'read' # 저장소 내용을 읽을 수 있는 권한
  packages: 'write' # github 패키지 레지스트리에 이미지를 푸시할 수 있는 권한


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository # 소스코드를 가져온다.
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build AI server with maven
        working-directory: ./ai/ai-server
        run: mvn --batch-mode --update-snapshots package -DskipTests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: chat-ai-server-webapp
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./ai/ai-server
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./ai/ai-server/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: chat-ai-server-webapp
        run: echo "REPO=chat-ai-server-webapp" >>${GITHUB_ENV}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_AI_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
      - name: Prevent push to main branch on deployment failure
        if: ${{ failure() }}
        run: |
          git checkout main
          git revert HEAD --no-edit
          git push origin main
