name: Frontend CI

on:
  push:
    tags:
      - "v*.*.*"
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: | 
            ${{ runner.os }}-node-
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Build with Node.js
        working-directory: ./frontend
        run: npm run build
        env:
          REACT_APP_SERVER_HOST: ${{ secrets.REACT_APP_SERVER_HOST }}
